# In ansible, if any of the task in the play fails, the subsequent tasks will fail
- name: Demo on errors
  hosts: all 
  tasks:
    - name: Check Tomcat Is Running or Not 
      ansible.builtin.shell: ps -ef | grep java | grep -v grep      
      register: OUT    
      ignore_errors: tr     # Errors wil be ignored by ansible for this task (When java is not running bash assumes it as failure as it fails to find that programme)

    - name: Run Shipping 
      ansible.builtin.debug:
        msg: Shipping is up 