# Copy is a module in ansible used to copy files from Ansible to remote servers

- name: Demo on copying files to remote servers 
  hosts: all 
  tasks:
    - name: copying the files
      ansible.builtin.copy:
        src: systemd.service
        dest: /home/centos